# Generated by Django 6.0.6 on 2026-06-20 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('marathon_daily', 'Marathon (daily)'), ('marathon_free', 'Marathon (free play)'), ('classic', 'Classic (daily)')], max_length=32)),
                ('score', models.IntegerField(default=0)),
                ('asset_version', models.IntegerField()),
                ('puzzle_date', models.DateField(blank=True, null=True)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['mode', 'puzzle_date', '-score'], name='scores_run_mode_400882_idx'), models.Index(fields=['user', 'mode'], name='scores_run_user_id_437399_idx')],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('marathon_daily', 'Marathon (daily)'), ('marathon_free', 'Marathon (free play)'), ('classic', 'Classic (daily)')], max_length=32)),
                ('current', models.IntegerField(default=0)),
                ('best', models.IntegerField(default=0)),
                ('last_played', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mode')},
            },
        ),
    ]
