# Generated by Django 6.0.6 on 2026-06-21 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='run',
            name='scores_run_mode_400882_idx',
        ),
        migrations.AddField(
            model_name='run',
            name='scope',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['mode', 'scope', 'puzzle_date', '-score'], name='scores_run_mode_f069d0_idx'),
        ),
    ]
