# Generated by Django 6.0.6 on 2026-06-21 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_remove_run_scores_run_mode_400882_idx_run_scope_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('marathon_daily', 'Marathon (daily)'), ('marathon_free', 'Marathon (free play)'), ('classic', 'Classic (daily)')], max_length=32)),
                ('species_key', models.CharField(max_length=128)),
                ('first_named_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='named_species', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'mode'], name='scores_name_user_id_1ab7a0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'mode', 'species_key'), name='uniq_user_mode_species')],
            },
        ),
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('marathon_daily', 'Marathon (daily)'), ('marathon_free', 'Marathon (free play)'), ('classic', 'Classic (daily)')], max_length=32)),
                ('games_played', models.IntegerField(default=0)),
                ('total_named', models.IntegerField(default=0)),
                ('unique_named', models.IntegerField(default=0)),
                ('best_score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mode_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mode')},
            },
        ),
    ]
