# Generated by Django 6.0.6 on 2026-06-21 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_namedspecies_playerstat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='run',
            name='scores_run_mode_f069d0_idx',
        ),
        migrations.AddField(
            model_name='run',
            name='difficulty',
            field=models.CharField(choices=[('common', 'Common names'), ('scientific', 'Scientific only')], default='common', max_length=16),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['mode', 'scope', 'difficulty', 'puzzle_date', '-score'], name='scores_run_mode_bec945_idx'),
        ),
    ]
