# Generated by Django 6.0.6 on 2026-06-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_remove_run_scores_run_mode_f069d0_idx_run_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('marathon_daily', 'Marathon (daily)'), ('marathon_free', 'Marathon (free play)'), ('classic', 'Classic (daily)')], max_length=32, unique=True)),
                ('label', models.CharField(help_text="Card title, e.g. 'Marathon'.", max_length=64)),
                ('blurb', models.CharField(blank=True, help_text='Card subtitle.', max_length=160)),
                ('route', models.CharField(default='/marathon', max_length=64)),
                ('enabled', models.BooleanField(default=False)),
                ('supports_difficulty', models.BooleanField(default=True, help_text='Whether Common/Scientific (and split boards) apply.')),
                ('sort_order', models.IntegerField(default=0, help_text='Lower sorts first on the Hub.')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
