# Generated by Django 6.0.6 on 2026-06-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_seed_game_modes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodeconfig',
            name='blurb',
            field=models.CharField(blank=True, help_text='Card subtitle.', max_length=240),
        ),
    ]
