# Generated by Django 6.0.6 on 2026-06-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0008_marathon_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='ranked',
            field=models.BooleanField(default=True),
        ),
    ]
