# Generated by Django 6.0.6 on 2026-06-21 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0009_run_ranked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='namedspecies',
            name='uniq_user_mode_species',
        ),
        migrations.RemoveIndex(
            model_name='namedspecies',
            name='scores_name_user_id_1ab7a0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='playerstat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='namedspecies',
            name='difficulty',
            field=models.CharField(choices=[('common', 'Common names'), ('scientific', 'Scientific only')], default='common', max_length=16),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='difficulty',
            field=models.CharField(choices=[('common', 'Common names'), ('scientific', 'Scientific only')], default='common', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='playerstat',
            unique_together={('user', 'mode', 'difficulty')},
        ),
        migrations.AddIndex(
            model_name='namedspecies',
            index=models.Index(fields=['user', 'mode', 'difficulty'], name='scores_name_user_id_b6c29b_idx'),
        ),
        migrations.AddConstraint(
            model_name='namedspecies',
            constraint=models.UniqueConstraint(fields=('user', 'mode', 'difficulty', 'species_key'), name='uniq_user_mode_difficulty_species'),
        ),
    ]
