# Generated by Django 6.0.6 on 2026-06-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0010_remove_namedspecies_uniq_user_mode_species_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The day this daily applies to.', unique=True)),
                ('mode', models.CharField(choices=[('marathon_daily', 'Marathon (daily)'), ('marathon_free', 'Marathon (free play)'), ('classic', 'Classic (daily)')], default='marathon_daily', max_length=32)),
                ('scope', models.CharField(help_text="AssetVersion scope key, e.g. 'aves'.", max_length=128)),
                ('note', models.CharField(blank=True, help_text='Optional admin note.', max_length=200)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyRotationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('marathon_daily', 'Marathon (daily)'), ('marathon_free', 'Marathon (free play)'), ('classic', 'Classic (daily)')], default='marathon_daily', help_text='The daily game for this entry (e.g. Marathon daily).', max_length=32)),
                ('scope', models.CharField(help_text="AssetVersion scope key, e.g. 'mammalia'.", max_length=128)),
                ('order', models.IntegerField(default=0, help_text='Rotation position (lower cycles first).')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Daily rotation entries',
                'ordering': ['order', 'scope'],
                'unique_together': {('mode', 'scope')},
            },
        ),
    ]
