# Generated by Django 6.0.6 on 2026-06-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0012_enable_daily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypin',
            name='date',
            field=models.DateField(help_text='The day this daily applies to.'),
        ),
        migrations.AlterUniqueTogether(
            name='dailypin',
            unique_together={('date', 'mode')},
        ),
    ]
