# Generated by Django 6.0.6 on 2026-06-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0014_rename_marathon_to_time_attack'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_layout', models.CharField(choices=[('radial', 'Radial'), ('rectangular', 'Phylogram')], default='radial', max_length=16)),
                ('show_scientific', models.BooleanField(default=True)),
                ('falling_leaves', models.BooleanField(default=True)),
                ('flash_fade_seconds', models.FloatField(default=2, help_text="How long a '+seconds' / 'no match' card lingers before fading.")),
                ('extant_only', models.BooleanField(default=True)),
                ('infinite_time', models.BooleanField(default=False)),
                ('start_seconds', models.IntegerField(default=60)),
                ('time_per_new', models.IntegerField(default=10)),
                ('novelty_bonus', models.IntegerField(default=8)),
                ('time_per_refinement', models.IntegerField(default=5)),
                ('combo_window_seconds', models.FloatField(default=6, help_text='Max gap (seconds) between placements to keep a combo alive.')),
                ('combo_time_multiplier', models.FloatField(default=1.5, help_text='Bonus seconds per combo step (× the combo level).')),
            ],
            options={
                'verbose_name': 'Game defaults',
                'verbose_name_plural': 'Game defaults',
            },
        ),
    ]
