# Generated by Django 6.0.6 on 2026-06-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0016_seed_game_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedefaults',
            name='combo_score_multiplier',
            field=models.FloatField(default=1.0, help_text='Bonus points per combo step (× the combo level); capped per placement.'),
        ),
    ]
