# Generated by Django 6.0.6 on 2026-06-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0017_gamedefaults_combo_score_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedefaults',
            name='clade_min_size',
            field=models.IntegerField(default=3, help_text='Smallest clade size that earns a completion bonus.'),
        ),
        migrations.AddField(
            model_name='gamedefaults',
            name='clade_score_multiplier',
            field=models.FloatField(default=2.0, help_text='Clade-completion bonus strength: points ≈ this × √(clade size). 0 disables.'),
        ),
    ]
