# Generated by Django 6.0.6 on 2026-06-25, then hand-edited to fold the old per-row
# NamedSpecies table into the new roaring-bitmap NamedSpeciesSet before dropping it (#55).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_sets(apps, schema_editor):
    """Fold every existing NamedSpecies row into the compact per-(user, mode, difficulty)
    roaring bitmap: intern each distinct species_key to a SpeciesToken id, then OR the ids
    into one NamedSpeciesSet per group."""
    from collections import defaultdict

    from pyroaring import BitMap

    NamedSpecies = apps.get_model("scores", "NamedSpecies")
    SpeciesToken = apps.get_model("scores", "SpeciesToken")
    NamedSpeciesSet = apps.get_model("scores", "NamedSpeciesSet")
    db = schema_editor.connection.alias

    keys = list(
        NamedSpecies.objects.using(db).values_list("species_key", flat=True).distinct()
    )
    if not keys:
        return
    SpeciesToken.objects.using(db).bulk_create(
        [SpeciesToken(species_key=k) for k in keys], ignore_conflicts=True
    )
    token_of = dict(
        SpeciesToken.objects.using(db)
        .filter(species_key__in=keys)
        .values_list("species_key", "id")
    )

    sets: dict[tuple, BitMap] = defaultdict(BitMap)
    for user_id, mode, difficulty, species_key in (
        NamedSpecies.objects.using(db)
        .values_list("user_id", "mode", "difficulty", "species_key")
        .iterator()
    ):
        tok = token_of.get(species_key)
        if tok is not None:
            sets[(user_id, mode, difficulty)].add(tok)

    NamedSpeciesSet.objects.using(db).bulk_create(
        [
            NamedSpeciesSet(
                user_id=u, mode=m, difficulty=d, bitmap=bm.serialize(), count=len(bm)
            )
            for (u, m, d), bm in sets.items()
        ]
    )


def unpopulate_sets(apps, schema_editor):
    """Reverse: rebuild NamedSpecies rows from the stored bitmaps (best-effort)."""
    from pyroaring import BitMap

    NamedSpecies = apps.get_model("scores", "NamedSpecies")
    SpeciesToken = apps.get_model("scores", "SpeciesToken")
    NamedSpeciesSet = apps.get_model("scores", "NamedSpeciesSet")
    db = schema_editor.connection.alias

    key_of = dict(SpeciesToken.objects.using(db).values_list("id", "species_key"))
    rows = []
    for s in NamedSpeciesSet.objects.using(db).iterator():
        bm = BitMap.deserialize(bytes(s.bitmap)) if s.bitmap else BitMap()
        for tok in bm:
            key = key_of.get(tok)
            if key:
                rows.append(
                    NamedSpecies(
                        user_id=s.user_id, mode=s.mode, difficulty=s.difficulty, species_key=key
                    )
                )
    NamedSpecies.objects.using(db).bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0018_gamedefaults_clade_min_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Create the new compact models.
        migrations.CreateModel(
            name='SpeciesToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('species_key', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NamedSpeciesSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('marathon_daily', 'Marathon (daily)'), ('marathon_free', 'Marathon (free play)'), ('classic', 'Classic (daily)')], max_length=32)),
                ('difficulty', models.CharField(choices=[('common', 'Common names'), ('scientific', 'Scientific only')], default='common', max_length=16)),
                ('bitmap', models.BinaryField(blank=True, default=bytes)),
                ('count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='named_species_sets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='namedspeciesset',
            constraint=models.UniqueConstraint(fields=('user', 'mode', 'difficulty'), name='uniq_named_set_user_mode_difficulty'),
        ),
        # 2. Migrate the data while the old table still exists.
        migrations.RunPython(populate_sets, unpopulate_sets),
        # 3. Drop the old per-row table.
        migrations.RemoveIndex(
            model_name='namedspecies',
            name='scores_name_user_id_b6c29b_idx',
        ),
        migrations.RemoveConstraint(
            model_name='namedspecies',
            name='uniq_user_mode_difficulty_species',
        ),
        migrations.RemoveField(
            model_name='namedspecies',
            name='user',
        ),
        migrations.DeleteModel(
            name='NamedSpecies',
        ),
    ]
