# Generated by Django 5.2.8 on 2026-06-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0021_gamedefaults_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedefaults',
            name='setting_multipliers',
            field=models.JSONField(blank=True, default=dict, help_text="Per-setting score derates: {settingKey: {kind: 'bool'|'linear', ...}}. Empty uses the built-in default ruleset (see multipliers.py)."),
        ),
        migrations.AddField(
            model_name='run',
            name='base_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='run',
            name='score_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.CreateModel(
            name='GameModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(default='marathon', help_text="Game key, e.g. 'marathon'.", max_length=32)),
                ('key', models.CharField(help_text="Stable id, e.g. 'blind'. Sent in the config.", max_length=32)),
                ('label', models.CharField(help_text="Lobby chip title, e.g. 'Blind'.", max_length=64)),
                ('blurb', models.CharField(blank=True, help_text='One-line description.', max_length=200)),
                ('multiplier', models.FloatField(default=1.0, help_text='Score multiplier when active. >1 harder/bonus, <1 easier.')),
                ('incompatible_with', models.JSONField(blank=True, default=list, help_text='List of modifier keys incompatible with this one.')),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower sorts first in the lobby.')),
            ],
            options={
                'ordering': ['sort_order', 'key'],
                'unique_together': {('game', 'key')},
            },
        ),
    ]
