# Generated by Django 5.2.8 on 2026-06-26 13:44

from django.db import migrations, models


def set_no_tree_hides(apps, schema_editor):
    # The seeded 'No tree' modifier hides the now-irrelevant tree-layout dial.
    GameModifier = apps.get_model("scores", "GameModifier")
    GameModifier.objects.filter(game="marathon", key="no_tree").update(
        hides_settings=["treeLayout"]
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0023_seed_no_tree_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodifier',
            name='forces_settings',
            field=models.JSONField(blank=True, default=dict, help_text="Settings pinned when active, e.g. {'infiniteTime': true}."),
        ),
        migrations.AddField(
            model_name='gamemodifier',
            name='hides_settings',
            field=models.JSONField(blank=True, default=list, help_text="Setting keys hidden when active, e.g. ['treeLayout']."),
        ),
        migrations.RunPython(set_no_tree_hides, noop),
    ]
