# Generated by Django 6.0.6 on 2026-06-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0025_seed_constraint_modifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='scope',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
