# Generated by Django 6.0.6 on 2026-07-20 16:37

import django.core.validators
from django.db import migrations, models


def seed_clash_row(apps, schema_editor):
    """Create the 'clash' GameDefaults row up front.

    GameDefaults.load() get_or_creates, so the row would appear the first time anyone opens
    Clade Clash — but then the admin has nothing to tune until someone plays, which is a
    confusing place to leave a knob we just added.
    """
    GameDefaults = apps.get_model("scores", "GameDefaults")
    GameDefaults.objects.get_or_create(game="clash")


def unseed_clash_row(apps, schema_editor):
    GameDefaults = apps.get_model("scores", "GameDefaults")
    GameDefaults.objects.filter(game="clash").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0029_unseed_clade_clash_versus'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedefaults',
            name='fame_bias',
            field=models.FloatField(default=0.6, help_text="Clade Clash: how strongly rounds favour well-known species. 0 = uniform (anything in the pack), 1 = strongly favour the most famous. The bias relaxes automatically if a fair round can't be formed.", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.RunPython(seed_clash_row, unseed_clash_row),
    ]
