# Generated by Django 6.0.6 on 2026-07-20 16:37

import django.core.validators
from django.core.management.color import no_style
from django.db import migrations, models


def seed_clash_row(apps, schema_editor):
    """Create the 'clash' GameDefaults row up front.

    GameDefaults.load() get_or_creates, so the row would appear the first time anyone opens
    Clade Clash — but then the admin has nothing to tune until someone plays, which is a
    confusing place to leave a knob we just added.

    Migration 0016 seeded the marathon row with an EXPLICIT pk (``get_or_create(pk=1)``),
    which does not advance Postgres' identity sequence — so the first *auto*-pk insert into
    this table asks for id=1 and collides. That is this insert, on every database migrated
    from scratch (a fresh deploy, CI, a new dev DB). Resync the sequence first.
    """
    GameDefaults = apps.get_model("scores", "GameDefaults")
    if GameDefaults.objects.filter(game="clash").exists():
        return
    sql = schema_editor.connection.ops.sequence_reset_sql(no_style(), [GameDefaults])
    with schema_editor.connection.cursor() as cursor:
        for statement in sql:
            cursor.execute(statement)
    GameDefaults.objects.create(game="clash")


def unseed_clash_row(apps, schema_editor):
    GameDefaults = apps.get_model("scores", "GameDefaults")
    GameDefaults.objects.filter(game="clash").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0029_unseed_clade_clash_versus'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedefaults',
            name='fame_bias',
            field=models.FloatField(default=0.6, help_text="Clade Clash: how strongly rounds favour well-known species. 0 = uniform (anything in the pack), 1 = strongly favour the most famous. The bias relaxes automatically if a fair round can't be formed.", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.RunPython(seed_clash_row, unseed_clash_row),
    ]
