# Generated by Django 5.2.8 on 2026-06-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(help_text='Plain text; blank lines separate paragraphs.')),
                ('order', models.IntegerField(default=0, help_text='Lower shows first.')),
                ('published', models.BooleanField(default=True, help_text='Untick to hide without deleting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ entry',
                'verbose_name_plural': 'FAQ entries',
                'ordering': ['order', 'id'],
            },
        ),
    ]
