# Generated by Django 6.0.6 on 2026-06-20 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=128)),
                ('version', models.IntegerField()),
                ('schema', models.CharField(default='1.0', max_length=16)),
                ('pool_size', models.IntegerField(default=0)),
                ('hidden_label_max', models.IntegerField(default=15)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('blob', models.JSONField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('built_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scope', '-version'],
                'indexes': [models.Index(fields=['is_current'], name='gamedata_as_is_curr_4ced7a_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'version'), name='uniq_scope_version'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('scope',), name='one_current_per_scope')],
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm', models.CharField(max_length=255)),
                ('target_key', models.CharField(max_length=128)),
                ('target_kind', models.CharField(choices=[('tip', 'tip'), ('node', 'node')], max_length=8)),
                ('sci', models.CharField(max_length=255)),
                ('common', models.CharField(blank=True, max_length=255, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_rows', to='gamedata.assetversion')),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'norm'], name='gamedata_al_asset_i_2581e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxonNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('rank', models.CharField(max_length=32)),
                ('sci', models.CharField(max_length=255)),
                ('common', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_key', models.CharField(blank=True, max_length=128, null=True)),
                ('pool_count', models.IntegerField(default=0)),
                ('depth', models.IntegerField(default=0)),
                ('lineage', models.JSONField(default=list)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tnodes', to='gamedata.assetversion')),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'key'], name='gamedata_ta_asset_i_1d7d59_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'key'), name='uniq_asset_node')],
            },
        ),
        migrations.CreateModel(
            name='TaxonTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('sci', models.CharField(max_length=255)),
                ('common', models.CharField(max_length=255)),
                ('parent_key', models.CharField(max_length=128)),
                ('lineage', models.JSONField(default=list)),
                ('traits', models.JSONField(default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttips', to='gamedata.assetversion')),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'key'], name='gamedata_ta_asset_i_89b27c_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'key'), name='uniq_asset_tip')],
            },
        ),
    ]
