# Generated by Django 6.0.6 on 2026-06-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0002_alias_trigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetversion',
            name='label',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='pool_size_extant',
            field=models.IntegerField(default=0),
        ),
    ]
