# Generated by Django 6.0.6 on 2026-06-21 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0003_assetversion_label_assetversion_pool_size_extant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(help_text="Asset scope id, e.g. 'fish'.", max_length=128)),
                ('label', models.CharField(blank=True, help_text="Display name, e.g. 'Fish'.", max_length=128)),
                ('scope_filter', models.CharField(help_text="CoL filter rank=value[,value…], e.g. 'class=Aves'.", max_length=512)),
                ('coldp_dir', models.CharField(default='data/coldp_col', max_length=256)),
                ('enrich', models.CharField(default='braidworks', max_length=16)),
                ('include_extinct', models.BooleanField(default=True)),
                ('load_current', models.BooleanField(default=True, help_text='After building, load the asset and mark it current.')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='gamedata_pi_status_72ce47_idx')],
            },
        ),
    ]
