# Generated by Django 6.0.6 on 2026-06-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0004_pipelinejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='kind',
            field=models.CharField(choices=[('build', 'Build asset'), ('fetch_dump', 'Download CoL dump')], default='build', help_text='Build an asset, or download a fresh CoL dump (replaces the old one). Download jobs ignore the scope fields.', max_length=16),
        ),
        migrations.AlterField(
            model_name='pipelinejob',
            name='scope_filter',
            field=models.CharField(blank=True, help_text="CoL filter rank=value[,value…], e.g. 'class=Aves'.", max_length=512),
        ),
        migrations.AlterField(
            model_name='pipelinejob',
            name='scope_key',
            field=models.CharField(blank=True, help_text="Asset scope id, e.g. 'fish'.", max_length=128),
        ),
    ]
