# Generated by Django 6.0.6 on 2026-06-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0006_pipelinejob_delete_old'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(help_text="Scope key the target lives in, e.g. 'aves'.", max_length=128)),
                ('name', models.CharField(help_text="What a player types, e.g. 'chicken'.", max_length=255)),
                ('norm', models.CharField(db_index=True, editable=False, max_length=255)),
                ('target_key', models.CharField(help_text="Target id, e.g. 'tip:Gallus_gallus' (browse Taxon tips to find it).", max_length=128)),
                ('target_kind', models.CharField(choices=[('tip', 'tip'), ('node', 'node')], default='tip', max_length=8)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Manual aliases',
                'constraints': [models.UniqueConstraint(fields=('scope', 'norm'), name='uniq_manual_alias')],
            },
        ),
    ]
