# Generated by Django 6.0.6 on 2026-06-24 23:22

from django.db import migrations, models
from django.db.models import F


def backfill_extant(apps, schema_editor):
    # Existing rows have no living-only count yet. Seed it with the full pool_count — a safe,
    # conservative default (clades never falsely read as "completed"); the next asset rebuild
    # populates the true extant figure via load_gamedata.
    TaxonNode = apps.get_model("gamedata", "TaxonNode")
    TaxonNode.objects.update(pool_count_extant=F("pool_count"))


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0007_manualalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonnode',
            name='pool_count_extant',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(backfill_extant, migrations.RunPython.noop),
    ]
