# Generated by Django 6.0.6 on 2026-06-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0008_taxonnode_pool_count_extant'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='fame',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxontip',
            name='fame',
            field=models.IntegerField(default=0),
        ),
    ]
