# Generated by Django 6.0.6 on 2026-06-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0009_alias_fame_taxontip_fame'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetversion',
            name='notable_count',
            field=models.IntegerField(default=0),
        ),
    ]
