# Generated by Django 6.0.6 on 2026-06-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0010_assetversion_notable_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='fame_dump',
            field=models.CharField(blank=True, default='', help_text='Optional path to a Wikimedia monthly pageview dump (pageviews-YYYYMM-user.bz2) for fame at huge-scope scale; blank uses the pageviews REST api.', max_length=256),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='frontier_rank',
            field=models.CharField(default='family', help_text="Coarse-backbone cut always shipped in the blob (and the deepest rank /resolve trims to), e.g. 'family'.", max_length=32),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='notable_coverage',
            field=models.FloatField(default=0.9, help_text='Fraction of total fame (≈pageview) mass the blob should cover; ≈ fraction of guesses served locally. Clamped to [min, max].'),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='notable_max',
            field=models.IntegerField(default=0, help_text='Max tips in the client blob; 0 = ship the whole pool (no remote tail). Suggested for huge scopes: ~20000.'),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='notable_min',
            field=models.IntegerField(default=5000, help_text='Floor on tips shipped, so a popularity-concentrated scope still ships a meaty offline pool.'),
        ),
    ]
