# Generated by Django 6.0.6 on 2026-06-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0011_pipelinejob_fame_dump_pipelinejob_frontier_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetversion',
            name='frontier_rank',
            field=models.CharField(default='family', max_length=32),
        ),
    ]
