# Generated by Django 6.0.6 on 2026-06-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0012_assetversion_frontier_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetversion',
            name='membership_filter',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
