# Generated by Django 6.0.6 on 2026-06-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0013_assetversion_membership_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='fame_month',
            field=models.IntegerField(default=0, help_text='Pageview dump month 1–12.'),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='fame_year',
            field=models.IntegerField(default=0, help_text='Pageview dump year, e.g. 2026.'),
        ),
        migrations.AlterField(
            model_name='pipelinejob',
            name='fame_dump',
            field=models.CharField(blank=True, default='', help_text="Optional path to an already-downloaded Wikimedia monthly pageview dump (pageviews-YYYYMM-user.bz2). Usually blank: once a 'Download pageview dump' job has built the local DB, every fame build reuses it automatically; blank with no prebuilt DB falls back to the per-title pageviews REST api.", max_length=256),
        ),
        migrations.AlterField(
            model_name='pipelinejob',
            name='kind',
            field=models.CharField(choices=[('build', 'Build asset'), ('fetch_dump', 'Download CoL dump'), ('fetch_pageviews', 'Download pageview dump')], default='build', help_text='Build an asset; download a fresh CoL dump (replaces the old one); or download + build the monthly Wikipedia pageview DB ONCE (then every fame build reuses it — the scalable path for huge scopes). Download jobs ignore the scope fields.', max_length=16),
        ),
    ]
