# Generated by Django 5.2.8 on 2026-06-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0014_pipelinejob_fame_month_pipelinejob_fame_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='fame_source',
            field=models.CharField(choices=[('auto', 'Auto (prebuilt DB → dump → REST)'), ('prebuilt', 'Prebuilt DB only (fail if missing)'), ('rest', 'REST api (force)')], default='auto', help_text="Which pageview backend fame uses. AUTO: prebuilt local DB if present, else a configured dump, else the slow per-title REST api. PREBUILT: the local DB ONLY — the build FAILS FAST if it's missing (so a huge scope never silently starts a multi-day REST crawl); use this for million-tip scopes after a 'Download pageview dump' job. REST: force the per-title api even when a DB exists.", max_length=16),
        ),
    ]
