# Generated by Django 6.0.6 on 2026-06-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0014_pipelinejob_fame_month_pipelinejob_fame_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DumpArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Absolute path on the worker volume.', max_length=512, unique=True)),
                ('kind', models.CharField(choices=[('coldp', 'CoL ColDP dump'), ('pageviews', 'Wikipedia pageview dump'), ('other', 'Other')], default='other', max_length=16)),
                ('label', models.CharField(blank=True, help_text='Friendly name (basename by default).', max_length=160)),
                ('size_bytes', models.BigIntegerField(default=0, help_text='Total size (recursive for a dir).')),
                ('present', models.BooleanField(default=True)),
                ('delete_pending', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['kind', 'path'],
            },
        ),
        migrations.CreateModel(
            name='PackSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable id, e.g. 'all-verts'.", max_length=64, unique=True)),
                ('label', models.CharField(help_text="Display name, e.g. 'All Vertebrates'.", max_length=80)),
                ('blurb', models.CharField(blank=True, help_text='One-line description.', max_length=200)),
                ('scopes', models.JSONField(default=list, help_text='List of scope keys this set bundles.')),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower sorts first in the lobby.')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='dump_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='pipelinejob',
            name='kind',
            field=models.CharField(choices=[('build', 'Build asset'), ('fetch_dump', 'Download CoL dump'), ('fetch_pageviews', 'Download pageview dump'), ('scan_dumps', 'Scan dumps on disk'), ('delete_dump', 'Delete a dump from disk')], default='build', help_text="Build an asset; download a fresh CoL dump (replaces the old one); download + build the monthly Wikipedia pageview DB ONCE (then every fame build reuses it — the scalable path for huge scopes); or scan/delete the dumps on the worker's disk. Download/scan/delete jobs ignore the scope fields.", max_length=16),
        ),
    ]
