# Generated by Django 6.0.7 on 2026-07-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0015_dumpartifact_packset_pipelinejob_dump_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='backfill_force',
            field=models.BooleanField(default=False, help_text='Backfill job: recompute even where the field is already present. For a backfiller whose RULE changed — not just to fill gaps.'),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='backfill_only',
            field=models.CharField(blank=True, default='', help_text="Backfill job: comma-separated field keys to fill (e.g. 'has_image'). Blank runs every backfiller. Leave scope_key blank to do EVERY scope.", max_length=128),
        ),
        migrations.AlterField(
            model_name='pipelinejob',
            name='kind',
            field=models.CharField(choices=[('build', 'Build asset'), ('fetch_dump', 'Download CoL dump'), ('fetch_pageviews', 'Download pageview dump'), ('scan_dumps', 'Scan dumps on disk'), ('delete_dump', 'Delete a dump from disk'), ('backfill', 'Backfill asset fields')], default='build', help_text="Build an asset; backfill fields a BUILT asset is missing (minutes, no dump — use this when a new per-tip field ships, not a full rebuild); download a fresh CoL dump (replaces the old one); download + build the monthly Wikipedia pageview DB ONCE (then every fame build reuses it — the scalable path for huge scopes); or scan/delete the dumps on the worker's disk. Download/scan/delete jobs ignore the scope fields.", max_length=16),
        ),
    ]
