# Generated by Django 6.0.6 on 2026-07-19 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=64, unique=True)),
                ('scope', models.CharField(max_length=512)),
                ('engine_id', models.CharField(default='rank-depth', max_length=32)),
                ('hp0', models.IntegerField(default=0)),
                ('hp1', models.IntegerField(default=0)),
                ('rounds', models.IntegerField(default=0)),
                ('ranked', models.BooleanField(default=False)),
                ('flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clash_as_p0', to=settings.AUTH_USER_MODEL)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clash_as_p1', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clash_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='clash_match_created_01cd31_idx')],
            },
        ),
    ]
